/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fatec.poo.view;

import fatec.poo.control.DaoPedido;
import fatec.poo.control.DaoCliente;
import fatec.poo.control.DaoVendedor;
import fatec.poo.control.PreparaConexao;
import fatec.poo.model.Cliente;
import fatec.poo.model.Pedido;
import fatec.poo.model.Vendedor;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author andremotoda
 */
public class GuiPedido extends javax.swing.JFrame {

    /**
     * Creates new form GuiCliente
     */
    public GuiPedido() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        txtCpfCliente1 = new javax.swing.JTextField();
        lblNomeCliente1 = new javax.swing.JLabel();
        btnConsultarCliente1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtDtEmissao = new javax.swing.JTextField();
        txtValor = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtCpfCliente = new javax.swing.JTextField();
        btnConsultar = new javax.swing.JButton();
        btnIncluir = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        lblNomeCliente = new javax.swing.JLabel();
        btnConsultarCliente = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtCpfVendedor = new javax.swing.JTextField();
        lblNomeVendedor = new javax.swing.JLabel();
        btnConsultarVendedor = new javax.swing.JButton();
        txtNumero = new javax.swing.JTextField();

        jLabel7.setText("CPF Cliente:");

        txtCpfCliente1.setText("jTextField1");
        txtCpfCliente1.setEnabled(false);

        lblNomeCliente1.setText("jLabel4");

        btnConsultarCliente1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnConsultarCliente1.setText("Consultar");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pedido");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Número do Pedido");

        jLabel2.setText("Data de Emissão");

        jLabel3.setText("Valor do Pedido");

        txtDtEmissao.setEnabled(false);

        txtValor.setEnabled(false);

        jLabel6.setText("CPF Cliente:");

        txtCpfCliente.setEnabled(false);

        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        btnIncluir.setText("Incluir");
        btnIncluir.setEnabled(false);
        btnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncluirActionPerformed(evt);
            }
        });

        btnAlterar.setText("Alterar");
        btnAlterar.setEnabled(false);
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.setEnabled(false);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        lblNomeCliente.setText("Nome Cliente");
        lblNomeCliente.setEnabled(false);

        btnConsultarCliente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnConsultarCliente.setText("Consultar");
        btnConsultarCliente.setEnabled(false);
        btnConsultarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarClienteActionPerformed(evt);
            }
        });

        jLabel10.setText("CPF Vendedor:");

        txtCpfVendedor.setEnabled(false);

        lblNomeVendedor.setText("Nome Vendedor");
        lblNomeVendedor.setEnabled(false);

        btnConsultarVendedor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnConsultarVendedor.setText("Consultar");
        btnConsultarVendedor.setEnabled(false);
        btnConsultarVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarVendedorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(btnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)
                            .addComponent(jLabel10))))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtCpfVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnConsultarVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblNomeVendedor))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtValor, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE)
                        .addComponent(txtDtEmissao)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(txtCpfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnConsultarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(lblNomeCliente)))
                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtDtEmissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(txtCpfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnConsultarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblNomeCliente)))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCpfVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(lblNomeVendedor)
                    .addComponent(btnConsultarVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConsultar)
                    .addComponent(btnIncluir)
                    .addComponent(btnAlterar)
                    .addComponent(btnExcluir)
                    .addComponent(btnSair))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        prepCon = new PreparaConexao("BD2223004","BD2223004");
        prepCon.setDriver("oracle.jdbc.driver.OracleDriver");
        prepCon.setConnectionString("jdbc:oracle:thin:@192.168.1.6:1521:xe");//"jdbc:oracle:thin:@192.168.1.6:1521:xe"
        daoPedido = new DaoPedido(prepCon.abrirConexao());
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        prepCon.fecharConexao();
    }//GEN-LAST:event_formWindowClosed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        pedido = null;
        pedido = daoPedido.consultar(txtNumero.getText());
        SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd ss:mm:hh");
        SimpleDateFormat df2 = new SimpleDateFormat("dd/MM/yyyy");
        
        if(pedido == null){
            txtNumero.setEnabled(false);
            txtDtEmissao.setEnabled(true);
            txtValor.setEnabled(true);
            txtCpfCliente.setEnabled(true);
            
            btnConsultarCliente.setEnabled(true);

            btnConsultar.setEnabled(false);
            btnIncluir.setEnabled(false);
            btnAlterar.setEnabled(false);
            btnExcluir.setEnabled(false);
        }
        else{
            Date dt = null;
            try {
                dt = df.parse(pedido.getDataEmissao());
            } catch (ParseException ex) {
                Logger.getLogger(GuiPedido.class.getName()).log(Level.SEVERE, null, ex);
            }
            txtDtEmissao.setText(String.valueOf(df2.format(dt)));
            txtValor.setText(String.valueOf(pedido.getValor()));
            txtCpfCliente.setText(pedido.getCliente().getCpf());
            txtCpfVendedor.setText(pedido.getVendedor().getCpf());
            lblNomeCliente.setText(pedido.getCliente().getNome());
            lblNomeVendedor.setText(pedido.getVendedor().getNome());
            
            btnConsultar.setEnabled(false);
            btnIncluir.setEnabled(false);
            btnAlterar.setEnabled(true);
            btnExcluir.setEnabled(true);
            
            txtDtEmissao.setEnabled(true);
            txtValor.setEnabled(true);
            txtCpfCliente.setEnabled(false);
            txtCpfVendedor.setEnabled(false);
            lblNomeCliente.setEnabled(true);
            lblNomeVendedor.setEnabled(true);
        }
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncluirActionPerformed
        pedido = new Pedido(txtNumero.getText());
        pedido.setDataEmissao(txtDtEmissao.getText());
        pedido.setValor(Double.parseDouble(txtValor.getText()));
        pedido.setCliente(new DaoCliente(prepCon.abrirConexao()).consultar(txtCpfCliente.getText()));
        pedido.setVendedor(new DaoVendedor(prepCon.abrirConexao()).consultar(txtCpfVendedor.getText()));
        daoPedido.incluir(pedido);
        
        txtNumero.setText(null);
        txtDtEmissao.setText(null);
        txtValor.setText(null);
        txtCpfCliente.setText(null);
        lblNomeCliente.setText(null);
        txtCpfVendedor.setText(null);
        lblNomeVendedor.setText(null);
        
        txtNumero.setEnabled(true);
        txtDtEmissao.setEnabled(false);
        txtValor.setEnabled(false);
        txtCpfCliente.setEnabled(false);
        txtCpfVendedor.setEnabled(false);
        lblNomeCliente.setEnabled(false);
        lblNomeVendedor.setEnabled(false);
        
        btnConsultar.setEnabled(true);
        btnConsultarCliente.setEnabled(false);
        btnConsultarVendedor.setEnabled(false);
        btnIncluir.setEnabled(false);
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);
    }//GEN-LAST:event_btnIncluirActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        if(JOptionPane.showConfirmDialog(null, "Confirma Alteração?") == 0){
            pedido.setValor(Double.parseDouble(txtValor.getText()));
            pedido.setDataEmissao(String.valueOf(txtDtEmissao.getText()));
            pedido.setCliente(new DaoCliente(prepCon.abrirConexao()).consultar(pedido.getCliente().getCpf()));
            pedido.setVendedor(new DaoVendedor(prepCon.abrirConexao()).consultar(pedido.getVendedor().getCpf()));
            
            daoPedido.alterar(pedido);
        }

        txtNumero.setText(null);
        txtDtEmissao.setText(null);
        txtValor.setText(null);
        txtCpfCliente.setText(null);
        lblNomeCliente.setText(null);
        txtCpfVendedor.setText(null);
        lblNomeVendedor.setText(null);
        
        txtNumero.setEnabled(true);
        txtDtEmissao.setEnabled(false);
        txtValor.setEnabled(false);
        txtCpfCliente.setEnabled(false);
        txtCpfVendedor.setEnabled(false);
        lblNomeCliente.setEnabled(false);
        lblNomeVendedor.setEnabled(false);
        
        btnConsultar.setEnabled(true);
        btnConsultarCliente.setEnabled(false);
        btnConsultarVendedor.setEnabled(false);
        btnIncluir.setEnabled(false);
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);

    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if(JOptionPane.showConfirmDialog(null, "Confirma Exclusão?") == 0){
            daoPedido.excluir(pedido);
        }
        txtNumero.setText(null);
        txtDtEmissao.setText(null);
        txtValor.setText(null);
        txtCpfCliente.setText(null);
        lblNomeCliente.setText(null);
        txtCpfVendedor.setText(null);
        lblNomeVendedor.setText(null);
        
        txtNumero.setEnabled(true);
        txtDtEmissao.setEnabled(false);
        txtValor.setEnabled(false);
        txtCpfCliente.setEnabled(false);
        txtCpfVendedor.setEnabled(false);
        lblNomeCliente.setEnabled(false);
        lblNomeVendedor.setEnabled(false);
        
        btnConsultar.setEnabled(true);
        btnConsultarCliente.setEnabled(false);
        btnConsultarVendedor.setEnabled(false);
        btnIncluir.setEnabled(false);
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);               
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnConsultarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarClienteActionPerformed
        cliente = new DaoCliente(prepCon.abrirConexao()).consultar(txtCpfCliente.getText());
        
        if(cliente == null){
            JOptionPane.showMessageDialog(null, "Cliente inválido");
        }
        else{
            txtCpfCliente.setEnabled(false);
            btnConsultarCliente.setEnabled(false);
            lblNomeCliente.setText(cliente.getNome());
            txtCpfVendedor.setEnabled(true);
            btnConsultarVendedor.setEnabled(true);
            lblNomeCliente.setEnabled(true);
        }
    }//GEN-LAST:event_btnConsultarClienteActionPerformed

    private void btnConsultarVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarVendedorActionPerformed
        vendedor = new DaoVendedor(prepCon.abrirConexao()).consultar(txtCpfVendedor.getText());
        
        if(vendedor == null){
            JOptionPane.showMessageDialog(null, "Vendedor inválido");
        }
        else{
            txtCpfVendedor.setEnabled(false);
            btnConsultarVendedor.setEnabled(false);
            lblNomeVendedor.setText(vendedor.getNome());
            btnConsultarVendedor.setEnabled(false);
            btnIncluir.setEnabled(true);
            lblNomeVendedor.setEnabled(true);
        }
        
    }//GEN-LAST:event_btnConsultarVendedorActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnConsultarCliente;
    private javax.swing.JButton btnConsultarCliente1;
    private javax.swing.JButton btnConsultarVendedor;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnIncluir;
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblNomeCliente;
    private javax.swing.JLabel lblNomeCliente1;
    private javax.swing.JLabel lblNomeVendedor;
    private javax.swing.JTextField txtCpfCliente;
    private javax.swing.JTextField txtCpfCliente1;
    private javax.swing.JTextField txtCpfVendedor;
    private javax.swing.JTextField txtDtEmissao;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
    private DaoPedido daoPedido=null;
    private Pedido pedido=null;
    private PreparaConexao prepCon=null;
    private Cliente cliente=null;
    private Vendedor vendedor=null;
}
